//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_tourist_routes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int IdFavorite { get; set; }
        public int IdUser { get; set; }
        public int IdRoute { get; set; }
        public Nullable<System.DateTime> DateAddedFavorite { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Users Users { get; set; }
    }
}
