//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_tourist_routes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hikes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hikes()
        {
            this.HikeParticipants = new HashSet<HikeParticipants>();
        }
    
        public int IdHike { get; set; }
        public Nullable<int> IdRoute { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string DescriptionHike { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
        public Nullable<System.DateTime> DateAddedHike { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HikeParticipants> HikeParticipants { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
