//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_tourist_routes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TouristRoutesEntities : DbContext
    {
        private static TouristRoutesEntities _context;
        public static TouristRoutesEntities GetContext()
        {
            if (_context == null) _context = new TouristRoutesEntities();
            return _context;
        }
        public static void DisposeContext()
        {
            if (_context != null)
            {
                _context.Dispose();
                _context = null;
            }
        }

        public TouristRoutesEntities()
            : base("name=TouristRoutesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<HikeParticipants> HikeParticipants { get; set; }
        public virtual DbSet<Hikes> Hikes { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<PointTypes> PointTypes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoutePoints> RoutePoints { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
