//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_tourist_routes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int IdPhoto { get; set; }
        public Nullable<int> IdRoute { get; set; }
        public string Photo { get; set; }
        public System.DateTime DateAddedPhoto { get; set; }
    
        public virtual Routes Routes { get; set; }
    }
}
