//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project_tourist_routes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelEvents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelEvents()
        {
            this.TravelParticipants = new HashSet<TravelParticipants>();
        }
    
        public int IdEvent { get; set; }
        public Nullable<int> IdRoute { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string TitleEvent { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int MaxParticipants { get; set; }
        public string StatusEvent { get; set; }
        public string DescriptionEvent { get; set; }
        public System.DateTime DateAddedEvent { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelParticipants> TravelParticipants { get; set; }
    }
}
